# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE UI will override any settings in this file.

# Specifying JVM memory arguments for Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Enables AndroidX support
android.useAndroidX=true

# Enables non-transitive R class for better build speed
android.nonTransitiveRClass=true

# Kotlin style
kotlin.code.style=official
